name: quiz_app
description: A new Flutter project

publish_to: 'none' # Remove this line if you want to publish to pub.dev

environment:
  sdk: ">=2.19.0 <3.0.0"  # SDK sürümü

dependencies:
  flutter:
    sdk: flutter
  font_awesome_flutter: ^10.1.0   # font_awesome_flutter ile sosyal medya ikonları
         # Google Fonts en güncel sürümü

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

